services:
  web-bot-client:
    container_name: web-bot-client
    restart: always
    image: node:20.12.2
    ports:
      - 3002:3002
    environment:
      - PORT=3002
    volumes:
      - ./:/usr/src/web-bot-client
    working_dir: /usr/src/web-bot-client

    networks:
      - web_client

    command: bash -c "npm install  && npm run build && npm run preview"

networks:
  web_client:
    driver: bridge
