version: "3.3"
services:
  next-app:
    container_name: web-app-client
    build: . # Ensure this points to the directory with your Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app # Only if you want to mount your local code for development
    environment:
      - NODE_ENV=production
